version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nginx_logs_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Set root password here
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: